---
kind: pipeline
name: deploy

steps:
- name: scp files
  image: appleboy/drone-scp
  settings:
    host: web.clemawe.com
    username:
      from_secret: deploy_user
    key: 
      from_secret: deploy_key
    port: 
      from_secret: deploy_port
    target: /var/www/clmns.dev/htlw3-medt
    source: "JavaScript/"
