--- 
pipeline: 
  deploy: 
    hosts: 
      - web.clemawe.com
    image: drillster/drone-rsync
    include: "*"
    key: 
      from_secret: deploy_key
    source: ./
    target: 
      from_secret: deploy_target
    when: 
      branch: master
      event: push
