---
kind: pipeline
name: deploy

platform:
  os: linux
  arch: arm

steps: 
  - name: scp files
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: deploy_host
      username: 
        from_secret: deploy_user
      key: 
        from_secret: deploy_key
      port: 
        from_secret: deploy_port
      target:
        from_secret: deploy_target
      source: "*"
