--- 
pipeline: 
  deploy: 
    hosts: 
      - web.clemawe.com
    image: drillster/drone-rsync
    include: "*"
    key: 
      from_secret: deploy_key
    script: 
      - "cd ~/packages"
      - "md5sum -c app.jar.md5"
    source: ./
    target: 
      from_secret: deploy_target
