--- 
kind: pipeline
name: deploy
steps: 
  - 
    image: drillster/drone-rsync
    name: deploy
    settings: 
      hosts: 
        - web.clemawe.com
      include: 
        - /
      exclude: [ ".gitignore", ".drone.yml", "_config.yml" ]
      key: 
        from_secret: deploy_key
      port: 
        from_secret: deploy_port
      target: 
        from_secret: deploy_target
      user: 
        from_secret: deploy_user
    when: 
      branch: master
      event: 
        - push
        - pull-request
trigger: 
  branch: 
    - master
